on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

name: tag-and-release
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      JRELEASER_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      JRELEASER_NEXUS2_USERNAME: ${{ secrets.OSSRH_USERNAME}}
      JRELEASER_NEXUS2_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      JRELEASER_VERSION: 1.17.0
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: install-java11
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: gradle-build-and-release
        run: ./gradlew --no-daemon --build-cache --scan -s clean publish jreleaserRelease
      - name: release-output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: upload-release-output
          path: |
            build/reports
            build/jreleaser/trace.log
            build/jreleaser/output.properties
